<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Tenguyama\Holidays\ViewModel\HolidayViewModel $_holidayViewModel */
    $_holidayViewModel = $block->getData('holiday_view_model');
    $attribute = $_holidayViewModel->getHolidayProductAttribute($_holidayViewModel->getCurrentProduct());
        if (!empty($attribute)) :
            ?>
            <div class="custom-product-attribute">
                <b><?= $attribute ?></b>
            </div>
        <?php endif; ?>
